#!/bin/sh

set -eux
cp -r tests "$AUTOPKGTEST_TMP"
cd "$AUTOPKGTEST_TMP"

export XDG_RUNTIME_DIR="$AUTOPKGTEST_TMP"

for python in $(py3versions -s); do
    dbus-run-session -- $python -m pytest -v tests/backends/test_SecretService.py
done
